text: |
  司会: こんにちは、生成AIポッドキャストへようこそ。今日は最新の生成AI技術と実用例についてお話しします。
  
  研究者: よろしくお願いします。まずは生成AIの基本的な仕組みと、ここ数年で起きた主要な進展について簡単に説明します。
  
  司会: 最近のモデルはどのように進化しているのでしょうか？創作や業務利用での変化が気になります。
  
  研究者: 大きなポイントは大規模事前学習、マルチモーダル対応、そして効率的な微調整手法の発展です。これによりテキスト生成だけでなく、画像や音声と組み合わせた応用が広がっています。
  
  司会: 実際のプロジェクトで役立つ事例はありますか？
  
  研究者: はい。コンテンツ自動生成、デザイン支援、コード生成、カスタマーサポートの自動応答など、多岐にわたります。ただし倫理やバイアス、データプライバシーの管理が重要です。
  
  司会: リスナーがこれから生成AIを学ぶための具体的なステップは？
  
  研究者: 理論の基礎を学びつつ、小さな実践プロジェクトを繰り返すことをおすすめします。また、倫理的配慮や検証方法も同時に学んでください。
  
  司会: 今日はありがとうございました。次回は応用事例の深掘りとハンズオンを予定しています。お楽しみに！

output: "outputs/generative_ai_podcast_2_speakers.wav"

instructions: |
  自然で会話的なトーンで話してください。
  司会と研究者の声色を明確に分け、スピーカ交代時に短い間（ポーズ）を入れてください。
  全体はプロフェッショナルかつ親しみやすく、説明部分はわかりやすく落ち着いたトーンでお願いします。
  各発話の最後にわずかな息継ぎを入れ、重要なポイントではやや強調してください。

model_config:
  name: "gemini-2.5-flash-preview-tts"
  config:
    multi_speaker: true
    speakers:
      - name: "司会"
        voice_name: "Achird"
        description: "親しみやすく落ち着いた女性の声"
      - name: "研究者"
        voice_name: "Charon"
        description: "知的で説明的な男性の声"
    response_format: "wav"